-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.branches (
  id integer NOT NULL DEFAULT nextval('branches_id_seq'::regclass),
  location character varying NOT NULL,
  CONSTRAINT branches_pkey PRIMARY KEY (id)
);
CREATE TABLE public.changelogs (
  id integer NOT NULL DEFAULT nextval('changelogs_id_seq'::regclass),
  title character varying NOT NULL,
  description text NOT NULL,
  version character varying NOT NULL,
  release_date date NOT NULL,
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  roles jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT changelogs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clients (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name character varying,
  contact_number character varying,
  email character varying,
  type text NOT NULL DEFAULT 'individual'::text CHECK (type = ANY (ARRAY['individual'::text, 'company'::text])),
  address text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  parent_client_id bigint,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_parent_client_id_fkey FOREIGN KEY (parent_client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.expenses (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  bill_name text,
  amount real,
  branch_id integer,
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.joborders (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  brand_model character varying,
  serial_number character varying,
  machine_type character varying,
  problem_statement text,
  additional_comments text,
  labor_description text,
  rate text,
  amount real,
  labor_total real,
  accessories text,
  material_total real,
  sub_total real,
  grand_total real,
  date_of_approval date,
  date_released date,
  client_id bigint,
  technician_id uuid,
  branch_id integer,
  order_no text UNIQUE,
  status text,
  warranty text,
  is_copy boolean,
  discount real,
  net_sales real,
  materials_expense real,
  technical_report text,
  order_received uuid,
  completed_at timestamp with time zone,
  downpayment real,
  payment_details jsonb,
  warranty_months integer,
  is_manual_rate boolean DEFAULT false,
  include_quotation_items boolean DEFAULT false,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT joborders_pkey PRIMARY KEY (id),
  CONSTRAINT JobOrder_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT joborders_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT joborders_order_received_fkey FOREIGN KEY (order_received) REFERENCES public.users(id),
  CONSTRAINT joborders_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.users(id),
  CONSTRAINT joborders_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.material_stocks (
  id integer NOT NULL DEFAULT nextval('material_stocks_id_seq'::regclass),
  material_name character varying NOT NULL,
  brand character varying NOT NULL,
  price numeric NOT NULL,
  stocks integer NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  last_stocks_added timestamp with time zone,
  sku character varying,
  category text,
  deleted boolean DEFAULT false,
  branch_id integer,
  cost real,
  CONSTRAINT material_stocks_pkey PRIMARY KEY (id),
  CONSTRAINT material_stocks_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.materials (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  material_description text,
  quantity integer,
  unit_price real,
  total_amount real,
  job_order_id bigint,
  material_id integer,
  used boolean,
  CONSTRAINT materials_pkey PRIMARY KEY (id),
  CONSTRAINT materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.material_stocks(id),
  CONSTRAINT materials_job_order_id_fkey FOREIGN KEY (job_order_id) REFERENCES public.joborders(id)
);
CREATE TABLE public.quotation_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  quotation_id bigint NOT NULL,
  description text NOT NULL,
  qty integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  amount numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  material_id text,
  is_manual boolean DEFAULT false,
  CONSTRAINT quotation_items_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_items_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotations(id) ON DELETE CASCADE
);
CREATE TABLE public.quotations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  quote_no text NOT NULL UNIQUE,
  job_order_id bigint NOT NULL,
  date_created timestamp with time zone DEFAULT now(),
  end_date date,
  company text,
  address text,
  note text,
  subtotal numeric DEFAULT 0,
  discount numeric DEFAULT 0,
  downpayment numeric NOT NULL DEFAULT 0,
  total_quote numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  labor_rate numeric DEFAULT 0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'for_approval'::text, 'approved'::text, 'rejected'::text, 'expired'::text])),
  is_active boolean DEFAULT true,
  is_final boolean DEFAULT false,
  service_fee numeric DEFAULT '0'::numeric,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  CONSTRAINT quotations_pkey PRIMARY KEY (id),
  CONSTRAINT quotations_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT quotations_job_order_id_fkey FOREIGN KEY (job_order_id) REFERENCES public.joborders(id) ON DELETE CASCADE
);
CREATE TABLE public.rental_assets (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  unit_name text NOT NULL,
  model text,
  serial_number text,
  daily_rate numeric NOT NULL DEFAULT 0,
  monthly_rate numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'available' CHECK (status IN ('available','rented','maintenance','retired')),
  branch_id integer NOT NULL,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted boolean NOT NULL DEFAULT false,
  CONSTRAINT rental_assets_pkey PRIMARY KEY (id),
  CONSTRAINT rental_assets_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.rentals (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  rental_no text UNIQUE,
  rental_asset_id integer NOT NULL,
  client_id bigint NOT NULL,
  technician_id uuid,
  branch_id integer NOT NULL,
  status text NOT NULL DEFAULT 'Created' CHECK (status IN ('Created','Released','Ongoing','Returned','Completed','Cancelled')),
  start_date date,
  end_date date,
  due_date date,
  is_overdue boolean NOT NULL DEFAULT false,
  rental_type text NOT NULL DEFAULT 'MONTHLY' CHECK (rental_type IN ('DAILY','MONTHLY')),
  rate_amount numeric NOT NULL DEFAULT 0,
  consumables_total numeric NOT NULL DEFAULT 0,
  grand_total numeric NOT NULL DEFAULT 0,
  notes text,
  billing_account_id uuid,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  deleted_by uuid,
  CONSTRAINT rentals_pkey PRIMARY KEY (id),
  CONSTRAINT rentals_rental_asset_id_fkey FOREIGN KEY (rental_asset_id) REFERENCES public.rental_assets(id),
  CONSTRAINT rentals_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT rentals_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES public.users(id),
  CONSTRAINT rentals_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT rentals_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.users(id),
  CONSTRAINT rentals_billing_account_id_fkey FOREIGN KEY (billing_account_id) REFERENCES public.billing_accounts(id),
  CONSTRAINT rentals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.rental_consumables (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  rental_id bigint NOT NULL,
  material_stock_id integer,
  description text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  is_manual boolean NOT NULL DEFAULT false,
  added_at timestamptz NOT NULL DEFAULT now(),
  notes text,
  CONSTRAINT rental_consumables_pkey PRIMARY KEY (id),
  CONSTRAINT rental_consumables_rental_id_fkey FOREIGN KEY (rental_id) REFERENCES public.rentals(id) ON DELETE CASCADE,
  CONSTRAINT rental_consumables_material_stock_id_fkey FOREIGN KEY (material_stock_id) REFERENCES public.material_stocks(id)
);
CREATE TABLE public.rental_inspections (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  rental_id bigint NOT NULL UNIQUE,
  physical_condition text,
  print_quality text,
  meter_reading_start integer,
  meter_reading_end integer,
  accessories_returned text,
  missing_items text,
  damage_assessment text,
  damage_penalty numeric DEFAULT 0,
  notes text,
  inspected_by uuid,
  inspected_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rental_inspections_pkey PRIMARY KEY (id),
  CONSTRAINT rental_inspections_rental_id_fkey FOREIGN KEY (rental_id) REFERENCES public.rentals(id) ON DELETE CASCADE,
  CONSTRAINT rental_inspections_inspected_by_fkey FOREIGN KEY (inspected_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text,
  role text,
  avatar text,
  fullname text,
  branch_id integer,
  shared_manager boolean DEFAULT false,
  deleted boolean DEFAULT false,
  must_change_password boolean DEFAULT false,
  migrated_email text,
  migration_status text DEFAULT 'pending'::text,
  migration_completed_at timestamp with time zone,
  migrated_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_branch_id_check CHECK (((branch_id IS NULL) OR (branch_id = ANY (ARRAY[1, 2])))),
  CONSTRAINT users_migrated_to_check CHECK (((migrated_to IS NULL) OR (migrated_to <> id))),
  CONSTRAINT users_migration_status_check CHECK ((migration_status = ANY (ARRAY['pending'::text, 'invited'::text, 'completed'::text]))),
  CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['dev'::text, 'admin'::text, 'manager'::text, 'technician'::text]))),
  CONSTRAINT users_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT users_migrated_to_fkey FOREIGN KEY (migrated_to) REFERENCES public.users(id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_auth_links (
  auth_user_id uuid NOT NULL,
  user_id uuid NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_auth_links_pkey PRIMARY KEY (auth_user_id, user_id),
  CONSTRAINT user_auth_links_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT user_auth_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
